<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/LSOverlay.Backend/LSOverlay.Backend.csproj" />
    <ProjectReference Include="../../../src/LSOverlay.RemoteClient/LSOverlay.RemoteClient.csproj" />
  </ItemGroup>
</Project>
