#include "core_wire.hpp"
#include "core_connection.hpp"
#include <fstream>
#include <iostream>
#include <iterator>

int main(int argc, char** argv) {
    unsigned checks = 0;
    auto check = [&](bool valid) { ++checks; if (!valid) throw std::runtime_error("Core wire assertion failed"); };
    auto rejects = [&](auto action) { bool rejected = false; try { action(); } catch (const std::exception&) { rejected = true; } check(rejected); };
    try {
        check(core::sha256({}) == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
        const std::vector<unsigned char> bytes{0,1,2,127,128,255};
        check(core::unbase64(core::base64(bytes)) == bytes);
        rejects([&] { (void)core::unbase64("AA==\n"); });
        rejects([&] { core::Json json("{\"a\":1,\"a\":2}"); });
        rejects([&] { core::Json json("{\"a\":{\"b\":1,\"b\":2}}"); });
        rejects([&] { core::Json json(std::string(10000,'[') + "0" + std::string(10000,']')); });
        rejects([&] { core::Json json("{\"a\":NaN}"); });
        rejects([&] { core::Json json(std::string("\"\xff\"",3)); });
        rejects([&] { core::Json json("{} trailing"); });
        core::Json exact("{\"n\":9223372036854775807}");
        check(core::numberField(exact.root(),"n") == INT64_MAX);
        rejects([&] { core::Json json("{\"n\":9223372036854775808}"); (void)core::numberField(json.root(),"n"); });
        core::SnapshotAssembler assembler;
        rejects([&] { (void)assembler.accept(std::string(core::maxFrameBytes+1,'x')); });
        check(assembler.pendingBytes() == 0);
        const auto now = core::CoreStreamState::Clock::now();
        const std::string heartbeat = "{\"protocolVersion\":1,\"type\":\"heartbeat\"}";
        std::optional<core::SnapshotDocument> current;
        core::CoreStreamState waiting(now);
        check(waiting.accept(heartbeat,current,now) == core::CoreFrameResult::heartbeat);
        rejects([&] { (void)waiting.accept(heartbeat,current,now+std::chrono::seconds(20)); });
        if (argc > 1) {
            // Fixture generated by the real .NET encoder, not a second C++ encoder.
            std::ifstream file(argv[1],std::ios::binary);
            if (!file) throw std::runtime_error("Core cross-language fixture missing");
            std::vector<std::string> frames;
            for (std::string line; std::getline(file,line);) if (!line.empty()) frames.push_back(std::move(line));
            check(frames.size() > 1);
            std::optional<core::SnapshotDocument> snapshot;
            for (std::size_t i = 0; i < frames.size(); ++i) {
                snapshot = assembler.accept(frames[i]);
                check(snapshot.has_value() == (i == frames.size()-1));
            }
            check(snapshot->revision == 9223372036854775806ULL);
            check(core::textField(snapshot->json->root(),"selfUserId") == "18446744073709551614");
            check(core::coreHello(&*snapshot).find("9223372036854775806") != std::string::npos);
            rejects([&] { (void)assembler.accept(frames[1]); });
            (void)assembler.accept(frames[0]);
            rejects([&] { (void)assembler.accept(frames[0]); });
            check(assembler.pendingBytes() == 0);
            auto corrupt = frames.back();
            const auto pos = corrupt.find("\"sha256\":\"");
            check(pos != std::string::npos);
            corrupt[pos+10] = corrupt[pos+10] == '0' ? '1' : '0';
            for (std::size_t i = 0; i + 1 < frames.size(); ++i) (void)assembler.accept(frames[i]);
            rejects([&] { (void)assembler.accept(corrupt); });
            check(assembler.pendingBytes() == 0);
            const std::string ready = "{\"protocolVersion\":1,\"type\":\"core_ready_v1\",\"generation\":" + core::jsonQuote(snapshot->generation) +
                ",\"revision\":" + std::to_string(snapshot->revision) + ",\"resumed\":false}";
            const std::string resumed = ready.substr(0,ready.size()-6) + "true}";
            core::CoreStreamState stream(now);
            for (const auto& frame : frames) {
                check(stream.accept(frame,current,now) == core::CoreFrameResult::pending);
                check(!current); // Even a complete doc is not published before matching Ready.
            }
            check(stream.accept(ready,current,now) == core::CoreFrameResult::ready && current.has_value());
            check(stream.accept(heartbeat,current,now+std::chrono::minutes(1)) == core::CoreFrameResult::heartbeat);
            core::CoreStreamState reconnect(now);
            check(reconnect.accept(resumed,current,now) == core::CoreFrameResult::resumed);
            core::CoreStreamState mixed(now);
            (void)mixed.accept(frames.front(),current,now);
            rejects([&] { (void)mixed.accept(resumed,current,now); });
            check(current->revision == snapshot->revision); // Last-good remains intact.
            core::CoreStreamState noSnapshot(now);
            rejects([&] { (void)noSnapshot.accept(ready,current,now); });
            core::CoreStreamState incomplete(now);
            (void)incomplete.accept(frames.front(),current,now);
            rejects([&] { (void)incomplete.accept(heartbeat,current,now+std::chrono::seconds(20)); });
            core::CoreStreamState mismatch(now);
            for (const auto& frame : frames) (void)mismatch.accept(frame,current,now);
            const auto wrong = "{\"protocolVersion\":1,\"type\":\"core_ready_v1\",\"generation\":\"wrong\",\"revision\":1,\"resumed\":false}";
            rejects([&] { (void)mismatch.accept(wrong,current,now); });
            check(current->revision == snapshot->revision);
        }
        std::cout << checks << " Core JSON/wire assertions passed\n";
        return 0;
    } catch (const std::exception& error) { std::cerr << error.what() << '\n'; return 1; }
}
