<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Gta/TranslationGlossary.ko.json" WithCulture="false" LogicalName="GachaOverlay.Core.Gta.TranslationGlossary.ko.json" />
  </ItemGroup>
</Project>
