<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GachaOverlay.Core\GachaOverlay.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sales\DefaultSalesProductCatalog.json" />
  </ItemGroup>
</Project>
